"""Renders STRATEGY_CATALOG.md from the 100 catalog/specs/*.yaml files --
generated, not hand-written, so it can never drift out of sync with the
actual specs the engine reads."""
from __future__ import annotations

from pathlib import Path

from botfarm.catalog.schema import SPECS_DIR, StrategySpec, load_all_specs

OUT_PATH = Path(__file__).resolve().parents[3] / "STRATEGY_CATALOG.md"

CATEGORY_TITLES = {
    "trend_following": "Trend Following",
    "mean_reversion": "Mean Reversion",
    "breakout_volatility": "Breakout / Volatility",
    "momentum_oscillator": "Momentum / Oscillator",
    "volume_orderflow": "Volume / Order Flow",
    "multi_indicator_confluence": "Multi-Indicator Confluence",
    "candlestick_pattern": "Candlestick Pattern",
    "statistical_zscore": "Statistical / Z-Score",
}


def _indicator_summary(spec: StrategySpec) -> str:
    if not spec.indicators:
        return "raw OHLC only"
    return ", ".join(f"{i.name}({i.alias})" for i in spec.indicators)


def render(specs: list[StrategySpec]) -> str:
    by_category: dict[str, list[StrategySpec]] = {}
    for s in specs:
        by_category.setdefault(s.category, []).append(s)

    lines = [
        "# Strategy Catalog",
        "",
        f"**{len(specs)} declarative strategies**, interpreted at runtime by "
        "`DeclarativeStrategy` (`src/botfarm/strategy/generic.py`) from the YAML "
        "specs in `src/botfarm/catalog/specs/`. Generated by "
        "`src/botfarm/catalog/generate_catalog_md.py` -- do not hand-edit this file, "
        "edit the specs (or `scripts/generate_strategy_catalog.py`, which produced "
        "them) and regenerate instead.",
        "",
        "**None of these have been individually backtested for edge.** Only bot #1 "
        "(a hand-picked, fully bespoke strategy, not from this catalog) has a real "
        "backtest report -- see `reports/bot01_mean_reversion/`. A handful of these "
        "specs were smoke-tested (`scripts/smoke_test_catalog.py`) only to confirm the "
        "engine runs them correctly end-to-end, not that any of them have an edge. "
        "Given the negative-expectancy finding documented for bot01 across 15 "
        "variants (see `docs/RISK_DISCLAIMER.md`), assume the same is likely true "
        "here until proven otherwise by an actual backtest.",
        "",
    ]

    for category, title in CATEGORY_TITLES.items():
        cat_specs = sorted(by_category.get(category, []), key=lambda s: s.id)
        lines.append(f"## {title} ({len(cat_specs)})")
        lines.append("")
        lines.append("| ID | Name | Timeframe | Indicators | Entry | Exit | Stop/Target (ATR mult) |")
        lines.append("|---|---|---|---|---|---|---|")
        for s in cat_specs:
            lines.append(
                f"| `{s.id}` | {s.name} | {s.timeframe} | {_indicator_summary(s)} "
                f"| `{s.entry_rule}` | `{s.exit_rule}` | {s.stop_loss_atr_mult} / {s.take_profit_atr_mult} |"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    specs = load_all_specs()
    content = render(specs)
    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(specs)} specs, {len(content.splitlines())} lines)")


if __name__ == "__main__":
    main()
